version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # Récupération du code source du repository
      - run:
          name: Run Unit Tests
          command: mvn test
      - codecov/codecov: # Exécution du script d'envoi de résultats à Codecov
          requires:
            - build # Attend la fin de la tâche de build

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
