version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Run Unit Tests with JaCoCo
          command: mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test
      - run:
          name: Generate JaCoCo Coverage Report
          command: mvn org.jacoco:jacoco-maven-plugin:report
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
