version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout # Récupération du code source du repository
      - run:
          name: Run Unit Tests
          command: mvn test

  upload-to-codecov:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - upload-to-codecov:
          jobs:
      - checkout
      - codecov/upload
